### ISSUE TITLE
Fine tuning Persian GPT-2 for Question Answering Task

### ISSUE THREAD

**Issue by alirezabayatmk** [hooshvare/parsgpt#1]
Is it possible to fine-tune the general Persian GPT-2 model on the question answering task with a custom dataset? I couldn't find any sources describing how to fine-tune a GPT model on a custom dataset. (except using the gpt-2-simple library which doesn't support Farsi or other huggingface models)

**Comment by m3hrdadfi** [comment]
It is already mentioned in the repo!
