### ISSUE TITLE
GPT ecco visualization not working

### ISSUE THREAD

**Issue by mitramir55** [hooshvare/parsgpt#3]
Hi, 

Firstly thank you very much for creating such amazing models and explanations of each. 

Secondly, I had to report a bug. In the `Persian GPT2 - Visualization.ipynb` notebook, after running the second cell (`lm = ecco.from_pretrained('HooshvareLab/gpt2-fa')`) we get the following error:

`The model 'HooshvareLab/gpt2-fa' is not defined in Ecco's 'model-config.yaml' file and so is not explicitly supported yet.`

I'd really appreciate it if you guys could take a look at this issue. The Ecco library can be a lot of help in understanding this model.

Thanks!

**Comment by m3hrdadfi** [comment]
Hi @mitramir55,

Thank you for your interest, and really thankful for the bug report!

Now you can clone the [notebook](https://colab.research.google.com/github/hooshvare/parsgpt/blob/master/notebooks/Persian_GPT2_Visualization.ipynb) on your Colab. Let me know if the issue is fixed!

**Comment by mitramir55** [comment]
Hi @m3hrdadfi,

Thanks for your reply! Now the second cell (where we import Hooshvare/gpt2-fa) can be run perfectly, but I'm not seeing any visualizations of the model after running the following cells. Maybe I'm missing something here. 

Here is one example:

![image](https://user-images.githubusercontent.com/53291220/112935376-e15b8680-9138-11eb-9a2e-5e712fc96c13.png)

**Comment by m3hrdadfi** [comment]
That's weird, and I think there may be some glitch in the Javascript part provided by Ecco. As always, the easiest way is to run the block multiple times (not a proper solution, but it works).

![screenshot](https://user-images.githubusercontent.com/2601833/112998390-49788f80-916e-11eb-81cf-583620d749aa.png)

**Comment by mitramir55** [comment]
Thanks @m3hrdadfi for the reply, although this still doesn't seem to work after several attempts. Although, I could go on with the implementation and fine-tuning of the model itself and figure out different aspects of it with the help of the other notebook you've provided 👍

**Comment by mitramir55** [comment]
Hi @m3hrdadfi, I just wanted to quickly say I could run the code properly and get the visualizations. This time I opened the notebook with a different VPN. Maybe this was the issue.
